"""Add is_active

Revision ID: f526df99dd65
Revises: 9d87f0721ccf
Create Date: 2026-08-29 20:33:22.365985
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f526df99dd65'
down_revision: Union[str, None] = '9d87f0721ccf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'candidate_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('applications', 'job_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('applications', 'status',
               existing_type=postgresql.ENUM('applied', 'shortlisted', 'rejected', 'interview', name='application_status'),
               nullable=False,
               existing_server_default=sa.text("'applied'::application_status"))
    op.alter_column('applications', 'applied_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint('uq_candidate_skill', 'candidate_skills', ['candidate_id', 'skill_id'])
    op.alter_column('certifications', 'candidate_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('education', 'candidate_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('experience', 'candidate_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('experience', 'is_current',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('fitment_results', 'job_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('fitment_results', 'candidate_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('fitment_results', 'computed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('job_postings', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('job_postings', 'num_openings',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('job_postings', 'status',
               existing_type=postgresql.ENUM('draft', 'live', 'closed', name='job_status'),
               nullable=False,
               existing_server_default=sa.text("'draft'::job_status"))
    op.alter_column('job_postings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('messages', 'sender_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('messages', 'sender_role',
               existing_type=postgresql.ENUM('candidate', 'company', 'admin', name='user_role'),
               nullable=False)
    op.alter_column('messages', 'sent_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('notifications', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('projects', 'candidate_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('resumes', 'candidate_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('resumes', 'content',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('resumes', 'version',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('resumes', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('resumes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('saved_jobs', 'saved_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('subscriptions', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('users', 'is_active')
    op.alter_column('subscriptions', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('saved_jobs', 'saved_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('resumes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('resumes', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('resumes', 'version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('resumes', 'content',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('resumes', 'candidate_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('projects', 'candidate_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('notifications', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('messages', 'sent_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('messages', 'sender_role',
               existing_type=postgresql.ENUM('candidate', 'company', 'admin', name='user_role'),
               nullable=True)
    op.alter_column('messages', 'sender_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('job_postings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('job_postings', 'status',
               existing_type=postgresql.ENUM('draft', 'live', 'closed', name='job_status'),
               nullable=True,
               existing_server_default=sa.text("'draft'::job_status"))
    op.alter_column('job_postings', 'num_openings',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('job_postings', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('fitment_results', 'computed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('fitment_results', 'candidate_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('fitment_results', 'job_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('experience', 'is_current',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('experience', 'candidate_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('education', 'candidate_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('certifications', 'candidate_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('uq_candidate_skill', 'candidate_skills', type_='unique')
    op.alter_column('applications', 'applied_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('applications', 'status',
               existing_type=postgresql.ENUM('applied', 'shortlisted', 'rejected', 'interview', name='application_status'),
               nullable=True,
               existing_server_default=sa.text("'applied'::application_status"))
    op.alter_column('applications', 'job_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('applications', 'candidate_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
